name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        working-directory: ./aplicacion
        run: npm ci

      - name: Construir la app
        working-directory: ./aplicacion
        run: npm run build
